import React from 'react';
import {Audio, Sequence, staticFile} from 'remotion';

/**
 * Sound wiring. No audio files ship with this repo, so every cue is gated on
 * `enabled` — with it false (the default) these render nothing and the video
 * stays silent instead of failing on a missing file.
 *
 * To turn sound on: drop the files listed in AUDIO_CUES into public/audio/,
 * then flip `enableAudio` to true in the Studio sidebar or defaultProps.
 *
 * Trim the leading silence off every SFX file before using it, otherwise the
 * hit lands late against the frame it is supposed to punctuate.
 */

export const AUDIO_CUES = {
  whoosh: 'audio/whoosh.mp3',
  tap: 'audio/tap.mp3',
  success: 'audio/success.mp3',
  notification: 'audio/notification.mp3',
  impact: 'audio/impact.mp3',
  music: 'audio/music-bed.mp3',
} as const;

export type AudioCue = keyof typeof AUDIO_CUES;

/** A one-shot cue fired `at` a frame offset inside the current scene. */
export const Sfx: React.FC<{
  enabled: boolean;
  cue: AudioCue;
  at: number;
  volume?: number;
}> = ({enabled, cue, at, volume = 0.7}) => {
  if (!enabled) return null;
  return (
    <Sequence from={at} name={`sfx-${cue}`}>
      <Audio src={staticFile(AUDIO_CUES[cue])} volume={volume} />
    </Sequence>
  );
};

/** Background music bed for the whole video, mixed low under narration. */
export const MusicBed: React.FC<{enabled: boolean; volume?: number}> = ({
  enabled,
  volume = 0.18,
}) => {
  if (!enabled) return null;
  return <Audio src={staticFile(AUDIO_CUES.music)} volume={volume} loop />;
};

/**
 * Per-scene narration — audio/vo-1.wav … audio/vo-9.wav, generated by
 * scripts/generate-vo-one.ps1 (Windows SAPI, word-level timing captured
 * alongside for the Captions component). This is real and wired in.
 */
export const Narration: React.FC<{enabled: boolean; scene: number; volume?: number}> = ({
  enabled,
  scene,
  volume = 1,
}) => {
  if (!enabled) return null;
  return <Audio src={staticFile(`audio/vo-${scene}.wav`)} volume={volume} />;
};
